PANTRY_CATEGORIES = {
    "Basic Seasonings": [
        "salt",
        "pepper",
        "sugar",
        "brown sugar",
    ],
    "Oils & Fats": [
        "olive oil",
        "vegetable oil",
        "canola oil",
        "coconut oil",
        "butter",
    ],
    "Core Sauces": [
        "soy sauce",
        "oyster sauce",
        "fish sauce",
        "worcestershire sauce",
        "hot sauce",
        "chili sauce",
        "barbecue sauce",
        "marinara sauce",
        "pasta sauce",
    ],
    "Vinegars & Acids": [
        "vinegar",
        "white vinegar",
        "balsamic vinegar",
        "apple cider vinegar",
        "red wine vinegar",
        "rice vinegar",
    ],
    "Condiments": [
        "ketchup",
        "mayonnaise",
        "mustard",
        "dijon mustard",
        "honey",
        "maple syrup",
    ],
    "Asian / Specialty": [
        "sesame oil",
        "hoisin sauce",
        "sriracha",
        "chili paste",
        "curry paste",
        "miso",
        "mirin",
    ],
    "Aromatics": [
        "garlic",
        "garlic powder",
        "onion",
        "onion powder",
        "ginger",
        "green onion",
    ],
    "Dried Herbs & Spices": [
        "thyme",
        "basil",
        "parsley",
    ],
}